<a href="https://colab.research.google.com/github/mbalbi/ciencia_de_datos/blob/main/tps/1c2025/ClaseApoyo20250318.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mi Titulo

Hola, como te va

## Cosa 1

Hola tambien

In [2]:
# una lista
A = [1, 3, 4, 5, 7, 10, 0]

# ver lista
print(A)

[1, 3, 4, 5, 7, 10, 0]


In [3]:
# un vector
import numpy as np

B = np.array(A)

# ver vector
print(B)

[ 1  3  4  5  7 10  0]


In [4]:
# las dimensiones de mi vector
B.shape

print(B.shape) # es un vector (1D)

(7,)


In [5]:
print(3>4)

False


In [7]:
print(bool(1))

True


In [13]:
print(B>3)

print(B<6)

[False False  True  True  True  True False]
[ True  True  True  True False False  True]


In [19]:
# Cumplir las dos condiciones
print((B>3) & (B<6)) # ejemplo, probabilidad conjunta
c = np.mean((B>3) & (B<6))

print(np.mean((B>3) & (B<6)))

# redondeo
print('La probabilidad de B>3 y B<6 es',np.round(c*100, 0),'%')

[False False  True  True False False False]
0.2857142857142857
La probabilidad de B>3 y B<6 es 29.0 %


P(B>3|B<6)

In [27]:
print(B[0:3]) # nota: el ultimo excluyente

[1 3 4]


In [30]:
B[[1,-1,0]]

array([3, 0, 1])

In [35]:
print(B)

filtro = B<6 # la condicion que quiero cumplir
print(filtro)

B_cond = B[filtro] # aplicar el filtro (booleanos) a mi vector

print(B_cond) # valores que cumplen condicion

# la probabilidad (condicionada)
#print(np.mean(B_cond>3))

[ 1  3  4  5  7 10  0]
[ True  True  True  True False False  True]
[1 3 4 5 0]


In [34]:
P_cond = np.mean(B[B<6]>3)

print('La probabilidad de B>3 dado B<6 es',np.round(P_cond*100, 0),'%')

La probabilidad de B>3 dado B<6 es 40.0 %


In [9]:
# cuantos verdaderos
np.sum(B>3)

print(np.sum(B>3))

4


In [12]:
# Probabilidad
P = np.sum(B>3)/len(B)

print(P)

print(np.mean(B>3))

0.5714285714285714
0.5714285714285714


In [38]:
# crear funciones Y = x^2
def Y(x):
    # funcion que eleva al cuadrado
    y_val = x**2
    return y_val # la potencia es **


In [39]:
print(Y(4))

16


In [42]:
# crear funcion simple Y = X**2
Y2 = lambda z: z**2 # esto es una funcion de x

print(Y2(4))

16


In [43]:
# el valor medio (por definicion) p(x) -->
# es la integral extendida al dominio x*p(x)*dx

#integrarles "analiticas" en python
import scipy as sp

# hagamos la integral de x*Y(x) entre 0 y 10 --> 10^4/4 = 2500
Int, err = sp.integrate.quad(lambda x: x*Y(x), 0, 10)

# varianza: integral extendida al domnio de (x-mu)**2 * p(x) * dx

# NOTA: El infinito np.inf en python

print(Int)

2500.0000000000005


In [46]:
def Plano(x,y):
  Z = 10*x+5*y
  return Z

La integral de Z entre X = [0,Y] con Y [-5,10]

*   Qué es en planta? --> Un triangulo



In [48]:
Int, err = sp.integrate.dblquad(lambda x,y: Plano(x,y),-5,10,0,lambda y: y)

print(Int)

3750.0
