<a href="https://colab.research.google.com/github/mbalbi/ciencia_de_datos/blob/main/tps/1c2024/Practica_0_completa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Listas y arrays




In [ ]:
# Una lista es una estructura de datos que aglomera cualquier tipo de elementos de manera ordenada, osea su posicion no varia. Permite modificar, agregar y eliminar datos.
List_empty = [] # Crea una lista vacia. Util cuando sabemos que vamos a querer ir "tirando" datos a una lista mediante un for loop.

A_empty = np.array([]) # Crea un array. Es similar a una lista pero permite almacenar una secuencia de elementos del mismo tipo (enteros, flotantes, etc)
print('Array vacio')
print(A_empty, type(A_empty))
print(' ')

# Crear un array de tamaño conocido 1D
A_4 = np.zeros(4)
print('Array de 4 (1D)')
print(A_4, type(A_4))
print(' ')

# Crear un array de tamaño conocido 2D
A_4= np.zeros((1,4))
print('Array de 1x4 (2D)')
print(A_4,type(A_4))
print(' ')

# Crear un array de tamaño conocido 2D
A_4= np.zeros((4,1))
print('Array de 4x1 (2D)')
print(A_4,type(A_4))
print(' ')

# Se puede generar un array de valores randoms
np.random.seed(0) #Al setearlo, genera siempre los mismos valores (aleatorios)
A_ran = np.random.uniform(0,5,len(A_4))
print('Array de 4 (1D)')
print(A_ran, type(A_ran))
print(' ')

A_ran44 = np.random.uniform(0, 5, (4,4))
print('Array de 4x4 (2D)')
print(A_ran44, type(A_ran44))

Array vacio
[] <class 'numpy.ndarray'>
 
Array de 4 (1D)
[0. 0. 0. 0.] <class 'numpy.ndarray'>
 
Array de 1x4 (2D)
[[0. 0. 0. 0.]] <class 'numpy.ndarray'>
 
Array de 4x1 (2D)
[[0.]
 [0.]
 [0.]
 [0.]] <class 'numpy.ndarray'>
 
Array de 4 (1D)
[2.74406752 3.57594683 3.01381688 2.72441591] <class 'numpy.ndarray'>
 
Array de 4x4 (2D)
[[2.118274   3.22947057 2.18793606 4.458865  ]
 [4.8183138  1.91720759 3.95862519 2.6444746 ]
 [2.84022281 4.62798319 0.35518029 0.4356465 ]
 [0.10109199 4.16309923 3.89078375 4.35006074]] <class 'numpy.ndarray'>


In [ ]:
#Como acceder a la informacion de un array

#Si es 1D
a_1D = np.array([7,8,9])
print('Array 1D:\n', a_1D)
print('Acceder al segundo valor: a_1D[1]:\n', a_1D[1])
print(' ')

#En una lista es exactamente igual.

#Si es 2D cambia en funcion de su estructura
a_3x1 = np.array([[7],[8],[9]])
print('Vector columna 3x1:\n', a_3x1)
print('Acceder al segundo valor: a_3x1[1,0]:\n', a_3x1[1,0])
print(' ')

a_1x3 = np.array([[7,8,9]])
print('Vector fila 1x3:\n', a_1x3)
print('Acceder al segundo valor: a_1x3[0,1]:\n', a_1x3[0,1])
print(' ')

#Tambien puedo acceder a una parte del array
Jorge = np.array([np.linspace(2,40,20)]) #Esto crea un array que empieza en 2 y termina en 40, dividido en 20 elementos.
print('Jorge es un array con 20 elementos:\n', Jorge)
print(' ')
print('A Jorge le quiero pedir los valores a partir del elemento 4:\n', Jorge[0,4:])
#RECORDAR: Python cuenta desde 0!!!
print(' ')
print('Ahora le pido los valores HASTA el elemento 8:\n', Jorge[0,:8])
print(' ')
print('Por ultimo, le pido los valores entre los elementos 4 y 8:\n', Jorge[0,4:8])

#Noten que no descarta el elemento ubicado en la posicion 4 y 8.






Array 1D:
 [7 8 9]
Acceder al segundo valor: a_1D[1]:
 8
 
Vector columna 3x1:
 [[7]
 [8]
 [9]]
Acceder al segundo valor: a_3x1[1,0]:
 8
 
Vector fila 1x3:
 [[7 8 9]]
Acceder al segundo valor: a_1x3[0,1]:
 8
 
Jorge es un array con 20 elementos:
 [[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36.
  38. 40.]]
 
A Jorge le quiero pedir los valores a partir del elemento 4:
 [10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40.]
 
Ahora le pido los valores HASTA el elemento 8:
 [ 2.  4.  6.  8. 10. 12. 14. 16.]
 
Por ultimo, le pido los valores entre los elementos 4 y 8:
 [10. 12. 14. 16.]


#Operaciones entre matrices


*   Broadcasting
*   Matriciales



In [ ]:
# Transponer una matriz
AT = A_ran44.T
print('A transpuesta:\n', AT)


#Python admite broadcasting, osea operaciones "punto a punto" cosa que el algebra pura no permite

#Creamos dos array
a = np.array([[1,2,3]])
b = np.array([[4],[5],[6]])
print('\nArray de 1x3:\n', a)
print('\nArray de 3x1:\n', b)


#Operaciones broadcasting

print('\nSuma punto a punto a + b\n', a + b)

print('\nMultiplicacion punto a punto a * b\n', a * b)

print('\nDivision punto a punto a / b\n', a / b)


# Operaciones matriciales

print('\nMultiplicacion entre matrices a@b\n', a @ b)

print('\nb@a\n', b@a)

print('\na + b^T\n', a + b.T)


A transpuesta:
 [[2.118274   4.8183138  2.84022281 0.10109199]
 [3.22947057 1.91720759 4.62798319 4.16309923]
 [2.18793606 3.95862519 0.35518029 3.89078375]
 [4.458865   2.6444746  0.4356465  4.35006074]]

Array de 1x3:
 [[1 2 3]]

Array de 3x1:
 [[4]
 [5]
 [6]]

Suma punto a punto a + b
 [[5 6 7]
 [6 7 8]
 [7 8 9]]

Multiplicacion punto a punto a * b
 [[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]

Division punto a punto a / b
 [[0.25       0.5        0.75      ]
 [0.2        0.4        0.6       ]
 [0.16666667 0.33333333 0.5       ]]

Multiplicacion entre matrices a@b
 [[32]]

b@a
 [[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]

a + b^T
 [[5 7 9]]


#Booleanos

In [ ]:
boolean = np.array([[False, True, False]]) #Crea un array logico, donde indica que el segundo elemento es true, el resto false.
print('Array logico:\n', boolean)

# Con este array puedo seleccionar valores de un array.
print('\nRecordemos que a = ', a)
print('Seleccion de valores true de a: ', a[boolean])

# Uso: Se puede elegir todos los valores de A menores a 3, por ejemplo.
boolmax2 = a<3
print('\nIndice logico de a<3: \n', boolmax2)
print('Valores de a<3: \n', a[boolmax2])
# Se puede indicar mas limites logicos:
boolnum1 = a<2
boolnum2 = a>=3
boolnum = boolnum1 | boolnum2 # | es el simbolo para un OR. El de AND es &
print('\nIndices logicos: ', boolnum)
print('Seleccion de a: ', a[boolnum])


#Supongamos que "b" es el vector tiempo y "a" es el vector datos.
#Puedo pedir que me devuelva los datos de a cuando b<6:
print('\nQue valor tiene a cuando b<6:\n', a[b.T<6]) #Recordar que son arrays 2D!!

Array logico:
 [[False  True False]]

Recordemos que a =  [[1 2 3]]
Seleccion de valores true de a:  [2]

Indice logico de a<3: 
 [[ True  True False]]
Valores de a<3: 
 [1 2]

Indices logicos:  [[ True False  True]]
Seleccion de a:  [1 3]

Que valor tiene a cuando b<6:
 [1 2]


#Datos utiles

In [ ]:
#Que es un range?
n = 8
j = range(2,8)
print('Lista j:', list(j))
print('Noten que va de 3 a 8. range NO incluye el ultimo valor')

#Puedo crear un array

j = np.array(range(2,8))
print('\narray j:', j)
print('forma j:', j.shape)

#Puede ser 2D
j_2D = np.array([range(2,8)])
print('\narray 2D j:', j_2D)
print('forma j:', j_2D.shape)

#Division
Div = n/j
print('\ndivision:', Div.round(2)) #redondea hasta el numero de cifras significativas indicado.

#Chequeo logico
resto = n%j
print('\nResto:', resto)

#Numero entero

check = resto == 0
print('\nCheck:', check)

#Los divisores (propios)
divprop = j[check]
print('\nDivisor propio:',divprop)
print('Divisor propio:',j[n%j == 0])

#Sumatoria de divisores
sumdiv = np.sum(divprop)
print('\nSumatoria de divisores', sumdiv)

Lista j: [2, 3, 4, 5, 6, 7]
Noten que va de 3 a 8. range NO incluye el ultimo valor

array j: [2 3 4 5 6 7]
forma j: (6,)

array 2D j: [[2 3 4 5 6 7]]
forma j: (1, 6)

division: [4.   2.67 2.   1.6  1.33 1.14]

Resto: [0 2 0 3 2 1]

Check: [ True False  True False False False]

Divisor propio: [2 4]
Divisor propio: [2 4]

Sumatoria de divisores 6


#For loops e ifs

In [ ]:
# un for loop facil:

for i in range((a.shape[1])):
  print(a[0,i])
  print('Hola, sigo con el siguiente valor de i')
print('Hola, terminé el for loop :)\n')

#Notar que la rutina no accede a las lineas posteriores al loop hasta que éste no termina.

#Con esto podemos separar entre pares e impares
for i in range(a.shape[1]):
  if a[0,i] / 2 == a[0,i] // 2:
    print('Es par:', a[0,i])
  else:
    print('Es impar:', a[0,i])

# otro ejemplo: calcular con un for loop la suma acumulada de a[0,i]^2

 #Creo un array vacio. Veamos como llenarlo con los valores que quiero.
asumb = np.array([])
for i in range(a.shape[1]):
  if i == 0:
    asumb = np.append(asumb, a[0,i] ** 2)
  else:
    asumb = np.append(asumb, np.sum(a[0, 0:i+1] ** 2))
print('\nEJERCICIO:\n')
print('Array a:', a)
print('Array de valores acumulados de a[0,i]^2:', asumb)

#Puedo operar con mi nuevo array creado!! Cuanto valores son pares de asumb?

boolcheck = asumb / 2 == asumb // 2
print('\nasumb = ',asumb)
print('Vector logico:\n',boolcheck)
print('Cantidad de valores pares es:', np.sum(boolcheck)) #osea, cantidades de True.

# otra forma: con dimensiones de array
print('\nCantidad de valores pares es:', len(asumb[boolcheck]))


1
Hola, sigo con el siguiente valor de i
2
Hola, sigo con el siguiente valor de i
3
Hola, sigo con el siguiente valor de i
Hola, terminé el for loop :)

Es impar: 1
Es par: 2
Es impar: 3

EJERCICIO:

Array a: [[1 2 3]]
Array de valores acumulados de a[0,i]^2: [ 1.  5. 14.]

asumb =  [ 1.  5. 14.]
Vector logico:
 [False False  True]
Cantidad de valores pares es: 1

Cantidad de valores pares es: 1


#Diccionarios

Estructura de datos que puede almacenar pares de elementos en forma de clave - valor. Esto quiere decir que puedo colocar dentro del diccionario arrays, listas, valores, etc. y a cada uno de ellos puedo acceder mediante una clave (key)

In [ ]:
#Creo varios arrays
a1 = np.array([[1,2,3,4]])
b1 = np.array([[5],[6],[7],[8]])
c1 = np.array([9,10,11,12])
#Se crea un diccionario
dicc = {
    'tiempo': a1,
    'desplazamiento': b1,
    'Jorge': c1
}
#Noten que se le asigna un nombre a cada elemento. Esta dispuesto asi por prolijidad,
#Es lo mismo que poner dicc = {'tiempo':a1,'desplazamiento':b1,'Jorge':c1}
print('Que hay dentro del dicc?\n',list(dicc))

#Como puedo acceder ahora a los datos "tiempo"?

tiempo = dicc['tiempo']
print('\ntiempo:', tiempo)

#Se puede crear un dicc vacio
dicc2 = {}
par = np.array([])
impar = np.array([])

vec = np.array([np.linspace(1,20,20)])
#Separemos en dos array los pares e impares, y guardemoslo en el diccionario vacio.

for i in range(vec.shape[1]):
  if vec[0,i] / 2 == vec[0,i] // 2:
    par = np.append(par, vec[0,i])
  else:
    impar = np.append(impar, vec[0,i])
dicc2['par'] = par
dicc2['impar'] = impar

print('\nDiccionario con arrays de pares e impares',list(dicc2))
print('Valores pares:', dicc2['par'])
print('Valores impares:', dicc2['impar'])
print('5to elemento del vector "par":', dicc2['par'][5])


Que hay dentro del dicc?
 ['tiempo', 'desplazamiento', 'Jorge']

tiempo: [[1 2 3 4]]

Diccionario con arrays de pares e impares ['par', 'impar']
Valores pares: [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
Valores impares: [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
5to elemento del vector "par": 12.0


In [ ]:
vec = np.array([np.linspace(2,40,20)])
vec.shape[1]

20

#Ejercicio
**Pongamos a prueba las herramientas de arriba**



Un número abundante se lo define como:

Un número cuya suma de divisores propios es mayor que el número mismo.
Ejemplo: 12 es divisible por 1, 2, 3, 4 y 6. La suma da 16>12. Es abundante Ejemplo: 15 es divisible por 1, 2, 3 y 5. La suma da 11<=15. No es abundante.

Actividad: Halle los el porcentaje de números abundantes entre 0 y 1000 y muestre los primeros 10. Indique el porcentaje de los que encontró que es par, y cuáles son los impares.

Bonus: halle los primeros 5 números abundantes impares

***Intenten hacerlo antes de mirar el resuelto***

A continuacion se presentan varias formas de resolver lo mismo. Hay muchos caminos de llegar al mismo resultado!!

In [ ]:
# Empiezo a tomar el tiempo para ver cuanto tarda
import time
start = time.time()

# Mi solucion
N = 1000
abundante = np.array([])
for n in range(N+1):
  num = np.array(range(n-1))+1
  DIV = num[n/num==n//num]

  if np.sum(DIV)>n:
    abundante = np.append(abundante,n)


end = time.time()
print('Tiempo total: ',end - start,'s')

print('los primeros 10 numeros abundantes son:',abundante[0:10])
print('el porcentaje de numeros abundantes entre 0 y 1000 es:',len(abundante)/(N+1))
print('el porcentaje de numeros pares abundantes entre 0 y 1000 es:',np.sum(abundante/2==abundante//2)/len(abundante))
print('los numeros abundantes impares entre 0 y 1000 son:',abundante[abundante/2!=abundante//2])

Tiempo total:  0.1441357135772705 s
los primeros 10 numeros abundantes son: [12. 18. 20. 24. 30. 36. 40. 42. 48. 54.]
el porcentaje de numeros abundantes entre 0 y 1000 es: 0.24575424575424576
el porcentaje de numeros pares abundantes entre 0 y 1000 es: 0.9959349593495935
los numeros abundantes impares entre 0 y 1000 son: [945.]


In [ ]:
# Empiezo a tomar el tiempo para ver cuanto tarda
import time
start = time.time()

# Mi solucion
abundante_impar = np.array([])
i=3
while len(abundante_impar)<5:
  num = np.array(range(i-1))+1
  DIV = num[i/num==i//num]
  suma = np.sum(DIV)
  check1 = suma>i
  check2 = i/2!=i//2

  if check1 & check2:
    abundante_impar = np.append(abundante_impar,i)

  i+=2

end = time.time()
print('Tiempo total: ',end - start,'s')

print('los primeros 5 numeros abundantes impares son:',abundante_impar)

Tiempo total:  0.984994649887085 s
los primeros 5 numeros abundantes impares son: [ 945. 1575. 2205. 2835. 3465.]


In [ ]:
# prompt: encontrar los numeros abundantes entre 0 y 1000

def is_abundant(n):
  """
  Checks if a number is abundant.

  Args:
      n: The number to check.

  Returns:
      True if the number is abundant, False otherwise.
  """

  # Find the divisors of n.
  divisors = [i for i in range(1, n) if n % i == 0]

  # Sum the divisors.
  sum_of_divisors = sum(divisors)

  # Check if the sum of the divisors is greater than n.
  return sum_of_divisors > n

# Find the abundant numbers between 0 and 1000.
abundant_numbers = [n for n in range(1, 1001) if is_abundant(n)]

# Print the abundant numbers.
print(abundant_numbers)


[12, 18, 20, 24, 30, 36, 40, 42, 48, 54, 56, 60, 66, 70, 72, 78, 80, 84, 88, 90, 96, 100, 102, 104, 108, 112, 114, 120, 126, 132, 138, 140, 144, 150, 156, 160, 162, 168, 174, 176, 180, 186, 192, 196, 198, 200, 204, 208, 210, 216, 220, 222, 224, 228, 234, 240, 246, 252, 258, 260, 264, 270, 272, 276, 280, 282, 288, 294, 300, 304, 306, 308, 312, 318, 320, 324, 330, 336, 340, 342, 348, 350, 352, 354, 360, 364, 366, 368, 372, 378, 380, 384, 390, 392, 396, 400, 402, 408, 414, 416, 420, 426, 432, 438, 440, 444, 448, 450, 456, 460, 462, 464, 468, 474, 476, 480, 486, 490, 492, 498, 500, 504, 510, 516, 520, 522, 528, 532, 534, 540, 544, 546, 550, 552, 558, 560, 564, 570, 572, 576, 580, 582, 588, 594, 600, 606, 608, 612, 616, 618, 620, 624, 630, 636, 640, 642, 644, 648, 650, 654, 660, 666, 672, 678, 680, 684, 690, 696, 700, 702, 704, 708, 714, 720, 726, 728, 732, 736, 738, 740, 744, 748, 750, 756, 760, 762, 768, 770, 774, 780, 784, 786, 792, 798, 800, 804, 810, 812, 816, 820, 822, 828, 832, 834, 

In [ ]:
# prompt: find the first five odd abundant numbers

def is_abundant(n):
    divisors = [i for i in range(1, n) if n % i == 0]
    return sum(divisors) > n

def is_odd(n):
    return n % 2 != 0

odd_abundant_numbers = []
n = 1
while len(odd_abundant_numbers) < 5:
    if is_abundant(n) and is_odd(n):
        odd_abundant_numbers.append(n)
    n += 1

print(odd_abundant_numbers)


[945, 1575, 2205, 2835, 3465]


Un alumno como ustedes (dia Lunes)

In [ ]:
import numpy as np

# Ejercicio
# Números abundantes
# Hallar los números abundantes entre 0 y 1000, mostar los primeros 10, porcentaje que es par, e impares

#tenemos 1001 números n 0 al 1000
#para cada número debo buscar los divisores
#que es un divisor? m es divisor de n si n/m = n//m, es lo mismo que decir que no tiene resto
#m va de (2:n) n exclusive

a = np.array([])                            # Creo  un vector vacío para guardar los números abundantes

n = 1001

for i in range(n) :                         # Para cada i en el rango n (de 0 a 1000)
  m = np.array(range(1,i))                  # El vector m son los números de 2 a i
  m = m[i/m == i//m]                        # Me quedo con los números del vector m que cumplen la condición de ser divisores de i
  suma = np.sum(m)                          # suma es el resultado de la suma de los números divisores de i, osea de los números del vector m
  if suma > i :                             # Si la suma es mayor que i
    a = np.append(a,i)                      # Agrego i al vector a

print('Vector de primeros 10 números abundantes : ',a[0:10])
print(' ')
N = len(a) #Cantidad de números abundantes
print('Cantidad de números abundantes entre 0 y 1000 : ',N)
print(' ')
print('Porcentaje de númros abundantes : ',np.round(N*100/n,3),'%')
print(' ')

pares = np.array([])                        # Creo un vector vacío para guardar los números abundantes pares
impares = np.array([])                      # Creo un vector vacío para guardar los números abundantes impares

for i in range(len(a)):                     # Para cada i en el rango N = len(a) (Cantidad de números abundantes)
  if a[i]/2 == a[i]//2:                     # Si el valor ai del vector de números abundantes (a) al dividirlo por 2 no tiene resto
    pares = np.append(pares,a[i])           # Agrego ai al vector pares
  else:                                     # Si el valor ai al dividirlo por 2 tiene resto
    impares = np.append(impares,a[i])       # Agrego ai al vector impares

print(len(pares),' son abundantes pares')
print(' ')
print(np.round(len(pares)*100/N,3),'% de los abundantes son pares')
print(' ')
print(len(impares),' son abundantes impares')
print(' ')
print(np.round(len(impares)*100/N,3),'% de los abundantes son impares')

Vector de primeros 10 números abundantes :  [12. 18. 20. 24. 30. 36. 40. 42. 48. 54.]
 
Cantidad de números abundantes entre 0 y 1000 :  246
 
Porcentaje de númros abundantes :  24.575 %
 
245  son abundantes pares
 
99.593 % de los abundantes son pares
 
1  son abundantes impares
 
0.407 % de los abundantes son impares


Una alumna como ustedes (dia Martes)

In [ ]:
import numpy as np
#Defino función checkabun. Esta función selecciona los números abundantes de un array.
#INPUT: número escalar, Abun np array
#OUTPUT: Abun array

def checkabun(n,Abun): #Def. función
  a=np.array(range(1,n)) #a es un array con los posibles divisores de n
  divisores=a[n%a==0] #divisores de n
  if np.sum(divisores)>n: #si la suma de los divisores de n es mayor que n
    Abun=np.append(Abun,n)  #agregar n a Abun
  return Abun  #acá no sé por qué va Abun???? D:

Abun20=np.array([])   #Defino Abun20 como un array vacío de tamaño desconocido
m=np.array(range(0,1001)) #Genero un array con el rango de números a analizar con mi función checkabun
for element in m: #para cada elemento de m
  Abun20=checkabun(element, Abun20)  #Valúo mi función en cada elemento y lo agrego a Abun20
#print(Abun20) #Imprimo mi lista de de números abundantes

#Calculo el porcentaje de Abundantes
porabun=len(Abun20)*100/1001
print("El porcentaje de números abundantes entre el 0 y el 1000 es:",porabun)

#Selecciono los primeros 10 números abundantes
print("Los primeros diez números abundantes son:",Abun20[:10]) #con el [:10] tomo los primeros 10 elementos

Abunpar=Abun20[Abun20%2==0] #array con los elementos pares de Abun20
#print(Abunpar[:10])
Abunimp=Abun20[Abun20%2!=0] #array con los elementos impares de Abun20
#print(Abunimp)

#Calculo el porcentaje de los abundantes pares e impares del 1 al 1000
porpar=len(Abunpar)*100/len(Abun20)
porimp=len(Abunimp)*100/len(Abun20)
print("El porcentaje de pares es", np.round(porpar,2), "% y el de impares", np.round(porimp,2),"%.") #imprimo y redondeo con 2 decimales

#BONUS
print("BONUS!!!")

Abunimp5=np.array([]) #defino array sin tamaño
numero_actual=0 #numero de partida
while len(Abunimp5) < 5: #mientras el tamano de Abunimp5 sea menor que 5
    #if (len(checkabun(numero_actual,Abunimp5))>len(Abunimp5)) & (numero_actual%2!=0): #chequeo abundancia para numeros impares
    if len(checkabun(numero_actual,Abunimp5))>len(Abunimp5) and numero_actual%2!=0: #es lo mismo de otra forma
        Abunimp5 = np.append(Abunimp5,numero_actual) #agrego los numeros impares abundantes
    numero_actual += 1  #sumo una unidad para pasar al siguiente numero
print("Los primeros 5 números abundantes impares son",Abunimp5,"!")

El porcentaje de números abundantes entre el 0 y el 1000 es: 24.575424575424574
Los primeros diez números abundantes son: [12. 18. 20. 24. 30. 36. 40. 42. 48. 54.]
El porcentaje de pares es 99.59 % y el de impares 0.41 %.
BONUS!!!
Los primeros 5 números abundantes impares son [ 945. 1575. 2205. 2835. 3465.] !


Más ejemplos

In [ ]:
import numpy as np # importo la libreria numpy
Abun = np.array ([]) # creo vector vacio donde incluire los valores de numeros abundantes
print (Abun)
[]
Div = np.array ([]) # creo vector vacio donde incluire los divisores de cada numero entre el 1 y el 1000
print (Div)
[]
i = 1

Abun = np.array ([])
for i in range (1, 1001):         # defino un for el cual barre los numeros desde el 1 al 1001 (excluyente)
  Div = np.array ([])
  for n in range (1, i):          # defino un for el cual barre los numeros desde el 1 al numero analizado en el for anterior (excluyente)
    if i//n == i/n:               # si la division redondea y la division con decimales es igual, n es divisor de i
      Div = np.append (Div, n)    # entonces agrego n al vector de divisores
  if np.sum(Div)>i:                  # si la suma de divisores es mayor que el numero, el numero es abundantes
    Abun = np.append (Abun, i)     # entonces agrego i al vector de numeros abundantes

AbunImp = Abun * (Abun/2 != Abun//2)   # busco los numeros impares multiplicando al vector por un vector del mismo tamaño que tiene la variable false en los lugares que hay numeros pares
AbunImp = AbunImp [AbunImp != 0]       # elimino los ceros

print ('Los numeros abundantes son', Abun)
print ()
print ('La cantidad de numeros abundantes entre el 0 y el 1000 es', len(Abun))
print ()
print ('Los numeros abundantes impares entre el 0 y el 1000 son', AbunImp)

In [ ]:
import numpy as np
n=1001
NumAb =[]
for i in range(n):
  m=np.array(range(2,i))
  m=m[i/m == i//m]
  sum = np.sum(m)
  if  sum > i:
   NumAb.append(i)
   i=i+1
  else:
    i=i+1
print('')
N=len(NumAb) #Cantidad de numeros abundantes
print('El porcentaje de numeros abundantes es',N/n)
print('Los primeros 10 valores son',NumAb[:10])
#Busco que porcentaje es par
Par=[] #me cree un vector de pares abundantes e impares abundantes
Impar=[]

for a in range(len(NumAb)):
  if (NumAb[a])/2 == (NumAb[a])//2:
    Par.append(NumAb[a])
    a=a+1
  else:
    Impar.append(NumAb[a])
    a=a+1
P=len(Par) #Cantidad de pares abundantes
I=len(Impar) #Cantidad de impares abundantes
print('El porcentaje de pares es',P*100/N, '%')
print('El porcentaje de impares es',(1-(P/N))*100 , '%')
print('El numero impar Abundante es',Impar)


El porcentaje de numeros abundantes es 0.24575424575424576
Los primeros 10 valores son [12, 18, 20, 24, 30, 36, 40, 42, 48, 54]
El porcentaje de pares es 99.59349593495935 %
El porcentaje de impares es 0.40650406504064707 %
El numero impar Abundante es [945]


In [ ]:
import numpy as np
#Ejercicio numeros abundantes del 1 al 1000, se imprimen los primeros 10
a = []
for n in range(1001):
  m = np.array(range(1,n)) #del 1 al n
  mask = (n/m == n//m)
  div = m[mask] #me quedo solamente con los divisores de n
  sumdiv = np.sum(div)
  if sumdiv > n:
    a.append(n)
a_10 = a[0:10]
print("Los primeros 10 numeros abundantes son:",a_10)

cant = len(a)
porcentaje_abundates = (cant/(n+1))*100
print("El porcentaje de los numeros abundantes entre el 0 y el 1000 es:",porcentaje_abundates)

impares = []
for n in a:
  if n/2 != n//2:
    	impares.append(n)
print("Los numeros abundantes impares entre el 0 y el 1000 son:",impares)

Los primeros 10 numeros abundantes son: [12, 18, 20, 24, 30, 36, 40, 42, 48, 54]
El porcentaje de los numeros abundantes entre el 0 y el 1000 es: 24.575424575424577
Los numeros abundantes impares entre el 0 y el 1000 son: [945]
