<a href="https://colab.research.google.com/github/mbalbi/ciencia_de_datos/blob/main/tps/1c2024/Practica_1_completa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 1: Introducción a Python

El objetivo de la clase de hoy es amigarnos un poco con Python como lenguage de programación y cubrir ciertas operaciones básicas a partir de las cuales iremos construyendo a lo largo del cuatrimestre.

Usamos Google Colab que nos permite programar y correr códigos de Python sin tener que preocuparnos por la instalación de python mismo o de programas específicos. A su vez, nos permite utilizar recursos de Google en la nube para el procesamiento, evitando así la necesidad de una computadora particularmente capaz.

Google Colab, como se ve, permite combinar texto y código de forma tal de generar reportes o documentos, y aprovecharemos esto para el desarrollo de los trabajos prácticos.

## Versión de Python

Una de las grandes ventajas de python es el número de librerías (por decirlo de alguna manera, paquetes de funciones) disponibles en forma libre que se ajustan a la medida del problema que tengamos que resolver. La contracara de esto es que se debe tener cuidado con la compatibilidad de estas librerías con la versión de python que se está corriendo.

En Google Colab se puede elegir la versión de python yendo a `Runtime --> Change Runtime Type`. Para verificar la misma, se puede hacer:

In [ ]:
!python --version

Python 3.10.12


No esperamos que a lo largo del curso nos encontremos con problemas de compatibilidad, pero sepan que puede ocurrir y tengan la costumbre de verificarlo.

Antes de empezar, sepan que tienen muchas herramientas a disposición para aprender. En el Campus, por ejemplo, hemos subido links a otros Notebooks de Google Colab para aprender con ejemplos.

Después, muchos de nosotros hemos aprendido a base de chocar con una pared, leer la documentación (la encuentran en el Campus también) y para alguna cosa más díficil buscar en Stack Exchange (no importa lo que están haciendo, alguien ya lo preguntó y se lo contestaron).

Además, si usan Google Colab desde su usuario personal (gmail), tienen acceso a `Colab AI`. ¡Pregúntenle algo y la inteligencia artificial te escribe código por vos! Puede llegar a halucinar un poco y tirarte código con bugs, pero es un buen punto de partida. A lo largo de esta clase iremos mostrando qué tipo de código entrega la IA.

## Introducción a Python

### Tipos de datos
Lo primero que tenemos que reconocer son los tipos de datos que podemos encontrarnos en Python.

#### Números

Por un lado tenemos los números: Números naturales (`integer`) y números reales (`float`). A diferencia de otros lenguages, la diferencia entre ambos es explícita en Python:

In [ ]:
a = 4 # a es un integer
b = 7. # b es un float

print(a)
print(b)

4
7.0


Podemos chequear el datatype de una variable con la función `type()`. Para ver el resultado que entrega la función, usaremos la función `print()`.

In [ ]:
print(type(a)) # Imprime el type de a
print(type(b)) # Imprime el type de b

<class 'int'>
<class 'float'>


Con los números se pueden realizar las operaciones matemáticas típicas (sumas, restas, multiplicaciones y divisiones).

In [ ]:
print(a + 1)   # Suma
print(a - 1)   # Resta
print(a * 2)   # Multiplicación
print(a ** 2)  # Potencia
#print(a ^ 2)   # Tira error
print(a / 2)   # División
print(type(a/2))

print(b + 1)   # Suma
print(b - 1)   # Resta
print(b * 2)   # Multiplicación
print(b ** 2)  # Potencia
print(b / 2)   # División

5
3
8
16
2.0
<class 'float'>
8.0
6.0
14.0
49.0
3.5


Noten que las operaciones aplican tanto para `integers` como `floats`. Sin embargo, la division de un `integer` da como resultado un `float`. Se debe tener cuidado con esto cuando este valor necesita ser un número natural (por ejemplo, para referirse a la columna de una matriz). Para convertir el valor, se puede usar la función `int()`, que trunca la variable al número entero.

In [ ]:
print(int(a/2))
print(int(b/2))

2
3


Otra opción es usar el operador `//`, que devuelve el mismo resultado que `int(x/y)` pero respeta el tipo de variable original.

In [ ]:
print(a // 2)
print(a // 2.0)
print(b // 5)
print(b // 5.0)
print((b/5)-(b//5)) #Quedarse con los decimales
print(b % 5) #El resto de la division

2
2.0
1.0
1.0
0.3999999999999999
2.0


Los resultados de las operaciones vistas arriba podemos guardarlos ya sea en nuevas variables como sobreescribiendo una ya existente. Para esto último existen formatos más compactos como se muestra a continuación.

In [ ]:
c = a + 2 # Suma 2 en una nueva variable 'c'
print(c)

a = a + 1 # Suma 1 y reemplaza a 'a'
print(a)

b += 1 # Suma 1 y reemplaza a 'b'
print(b)

b *= 2 # Multiplica por 2 y reemplaza a 'b'
print(b)

6
5
8.0
16.0


Honestamente, para empezar es preferible hacer la forma "larga", además es más legible.

#### Texto

El otro tipo de variable que nos encontramos seguido es el Texto (`string`). Si bien no solemos realizar muchas operaciones con variables de texto propiamente dichas, la suma de las mismas resulta en un concatenamiento.

In [ ]:
hello = 'hello' # ''
world = "world" # "" es lo mismo, no importa
Oracion = hello + ' ' + world + '!'
print(Oracion)

hello world!


#### Variables lógicas
Python permite a su vez trabajar con variables booleanas (`True` y `False`) para verificar si se cumplen ciertas condiciones:

In [ ]:
t, f = True, False
print(type(t))

<class 'bool'>


Las distintas operaciones booleanas (AND, OR, NOT, XOR) se encuentran todas definidas. Como recordartorio, AND es `True` cuando ambas variables son `True`, OR es `True` si alguna de las variables es `True`, NOT es `True` cuando una variable es `False`, y XOR es `True` cuando dos variables son distintas.

In [ ]:
print(t and f) # AND
print(t or f) # OR
print(not t) # NOT
print(t == f)
print(t != f) # XOR

False
True
False
False
True


Las variables lógicas se obienen también como resultado de comparaciones de otro tipos de datos. por ejemplo, números, y son muy útiles para explorar datos y generar filtros.

In [ ]:
print(3 > 3)
print(3 >= 3)
print(5 != 3)
print('hola' == 'hola')
print('hola' == 'chau')
print(5 > 3 and 3 < 1)

False
True
True
True
False
False


### Listas

Una lista es un conjunto arreglado de items, los cuales pueden ser cualquiera de los tipos de datos vistos anteriormente (incluso combinaciones)

In [ ]:
a = [1, 2, 3, 4]
b = [True, 'Perro', 5, 4.0]
c = [[1, 2],[3, 4]]

print(a)
print(b)
print(c)

# a = [1, 3, 4, 5] #Me alcanza? Separen con coma

[1, 2, 3, 4]
[True, 'Perro', 5, 4.0]
[[1, 2], [3, 4]]


Los valores de una lista están indexados de 0 a la longitud de la lista. Esta última puede ser encontrada con la función `len()`. Noten que la longitud de c es dos ya que tiene dos listas dentro de la lista.

In [ ]:
print(len(a))
print(len(b))
print(len(c))

4
4
2


Valores específicos de la lista pueden ser extraídos refiriendose al índice requerido. Una ventaja de python es que números negativos comienzan el conteo desde el final (por ejemplo, -1 es el último lugar de la lista), lo que simplifica el código en algunas situaciones, y evita calcular la longitud de la lista.

In [ ]:
print(a[len(a)-1]) #El ultimo
print(a[-2]) # el anteultimo

4
3


In [ ]:
print(a[-1]) # último lugar
print(b[1])  # segundo lugar
print(c[0])  # primer lugar
print(c[0][1]) # toma el segundo valor de la primer lista

4
Perro
[1, 2]
2


También puede tomarse un slice (un conjunto de la lista) de las siguientes formas:

In [ ]:
print(a[1:]) # toma todos los valores a partir del segundo
print(b[0:2]) # toma los dos primeros valores (el tercero excluido)

[2, 3, 4]
[True, 'Perro']


La indexación puede utilizarse cambiar valores de la lista:

In [ ]:
a[3] = '40'
print(a)

b[:2] = ['Hello', 57] #tengan mucho cuidado con la compatibilidad de dimensiones
# Prueben correr varias veces
print(b)

[1, 2, 3, '40']
['Hello', 57, 5, 4.0]


Se debe tener cuidado en Python ya que las listas ocupan un mismo espacio en la memoria. Por ejemplo `a = b`hace que ambas variables se refieran al mismo lugar: si cambio una de ellas, ambas lo harán. Veamos el siguiente ejemplo, donde aprenderemos también a agregar items a una lista.

CON NUMEROS

In [ ]:
a = 5
b = a

a = 6
print(b) # me va a dar 5, no cambio b

5


CON LISTAS (son dos formas distintas de referir a la misma variable)

In [ ]:
a = [1, 2, 3, 4] # Defino a
b = a            # b es igual a a
a.append(5)      # Modifico a, agrego 5 al final
print(b)         # b cambia!
b.append(6)      # Modifico b, agrego 6 al final
print(a)         # a cambia!

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


Si esto no es deseable, se debe usar la función `copy()`, que genera una copia de los valores en otro lugar de la memoria:

In [ ]:
a = [1, 2, 3, 4] # Defino a
b = a.copy()     # b es una copia de a
a.append(5)      # Modifico a, agrego 5 al final
print(b)         # b sigue igual!
b.append(6)      # Modifico b, agrego 6 al final
print(a)         # a sigue igual!

# UNA LISTA NO ES MATRIZ
print(a+b) # es una concatenacion

[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 6]


Como recomendación, en general en el curso vamos a trabajar con vectores y matrices. Por ello, les recomendamos evitar las listas en la medida de lo posible. En un rato vamos a ver como convertir las listas en algo más útil para nosotros.

### Diccionarios

Un diccionario es también un arreglo de items pero que, en vez de trabajar con indices, utiliza palabras clave (llaves/keys) y valores. Por ejemplo, si mi diccionario es un dataset de lluvias, podría tener información acerca de la latitud y longitud de la estación, su nombre, un registro de lluvias diarias, y un indicador de las unidades de trabajo:

In [ ]:
Lluvias = {'estacion':[7.52, -14.4],'ID':'San Rafael', 'data':[3, 4, 0, 0, 5],
           'unidades':'mm/dia'}

Se puede acceder a los datos del dicionario de varias formas:

In [ ]:
print(Lluvias['ID'])
print(Lluvias.get('data'))

San Rafael
[3, 4, 0, 0, 5]


Imaginemos que tenemos un nuevo dato de lluvia y queremos agregarlo, y además queremos agregar un listado de temperaturas. Para ello podemos hacer

In [ ]:
Lluvias['data'] += [0, 1]
print(Lluvias['data'])

# crea nueva palabra clave en el diccionario
Lluvias['Temp'] = [30, 20, 25, 10, 0]
print(Lluvias['Temp'])

[3, 4, 0, 0, 5, 0, 1]
[30, 20, 25, 10, 0]


A lo largo del curso muchos datasets se van a parecer **mucho** a un diccionario, por lo que ir entendiendo este lenguaje es importante.

### Condicionales e iteraciones

En el ejemplo anterior incorporamos valores o creamos una nueva entrada en el diccionario asumiendo que ya sabíamos que existía o no lo que necesitabamos. En el caso general, sería necesario revisar esto para no generar problemas. Podemos usar entonces `if` statements con ese fin, con el código realizando la operación conveniente en cada caso:

In [ ]:
print('Amor' in Lluvias)
print(5 in [1, 5, 3, 4])

False
True


In [ ]:
Lluvias = {'estacion':[7.52, -14.4],'ID':'San Rafael', 'data':[3, 4, 0, 0, 5],
           'unidades':'mm/dia'}


if 'data' in Lluvias:       # Chequea si existe una llave data
  Lluvias['data'] += [0, 1]  # Agrega valores
else:                       # Caso contrario
  Lluvias['data'] = [0, 1]   # Crea una nueva entrada

print(Lluvias['data'])

if 'temp' in Lluvias:       # Chequea si existe una llave data
  Lluvias['temp'] += [30, 20, 25, 10, 0]  # Agrega valores
else:                       # Caso contrario

  Lluvias['temp'] = [30, 20, 25, 10, 0]   # Crea una nueva entrada

print(Lluvias['temp'])

if 'temp' in Lluvias:
  print('es cierto')
else:
  print('no es cierto')
print('se imprime igual') # distintas indentaciones

[3, 4, 0, 0, 5, 0, 1]
[30, 20, 25, 10, 0]
es cierto
se imprime igual


NOTA: No necesariamente debe incluirse un `else`. Acá aparece porque hay algo para hacer si el `if` es falso.

También existe `elif`, que en forma jerárquica aplica un `if` **solo** sí el `if` anterior fue falso. Caso contrario no lo tiene en cuenta.

In [ ]:
a = 0
if a>5:
  print('Es mayor que 10')
elif a>2:
  print('Es mayor que 2')

Es importante notar que Python trabaja con indentaciones. Es decir, luego de colocar el statement `if` este se debe terminar con dos puntos, y luego TODO lo que se encuentre indentado (con la misma indentación) se lo considera dentro de ese bloque if. El final de bloque no se indica explicitiamente, sino simplemente terminando la indentación.

Si quisieramos iterar a traves de los valores de una lista, podemos utilizar distintas estrategias, mostradas a continuación que muestran la eficiencia de Python para tomar valores y simplificar la notación:

In [ ]:
a = [1, 3, 5, 7]

i = 0 # Definir una variable para recorrer los indices
while i < len(a): # Mientras la variable este dentro del rango
  print(i, a[i]) # Imprimir indice y valor de la lista
  i += 1

print(' ')
for i in range(len(a)): # Generar una iteracion entre los indices de la lista
  print(i, a[i]) # Imprimir indice y valor

print(' ')
for idx,ai in enumerate(a): # Extraer los indices y valores de la lista
  print(idx, ai) # Imprimir indice y valor

0 1
1 3
2 5
3 7
 
0 1
1 3
2 5
3 7
 
0 1
1 3
2 5
3 7


El último método mostrado es particularmente potente, y muy útil para diccionarios. Compare el código en estos dos ejemplos:

In [ ]:
Lluvias = {'estacion':[7.52, -14.4],'ID':'San Rafael', 'data':[3, 4, 0, 0, 5],
           'unidades':'mm/dia'}

for i in range(len(Lluvias)):
  print(list(Lluvias.keys())[i], Lluvias[list(Lluvias.keys())[i]])

print(' ')
# ASI SE HACE BIEN Y FACIL
for keys in Lluvias:
  print(keys, Lluvias[keys])

estacion [7.52, -14.4]
ID San Rafael
data [3, 4, 0, 0, 5]
unidades mm/dia
 
estacion [7.52, -14.4]
ID San Rafael
data [3, 4, 0, 0, 5]
unidades mm/dia


Esto solía ser más importante en versiones anteriores de Python cuando los diccionarios eran "no ordenados". En las últimas versiones los diccionarios son ordenados igual que las listas, por lo que la indexación funciona.

### Numpy

Mencionamos antes que existen varias librerías de Python que incorporan funcionalides clave para la solución de problemas. La principal es Numpy, que incopora un nuevo tipo de data (`arrays`) y muchas herramientas de operación matricial. Para agregar una librería en su conjunto, se hace lo siguiente.

In [ ]:
import numpy as np

Numpy va a hacer **Clave**. Todo lo que hagamos vamos a tratar de que tenga forma de Numpy array prácticamente, evitando las listas. ¿Por qué? Porque trabajamos con números (vectores y matrices)

Un array se crea a partir de una lista de Python, y es a fin de cuentas una matriz. La principal diferencia con otros lenguajes es que, en python, los arrays 1-D no differencian entre vectores columna y vectores filas. Si se quiere especificar, se debe crear un array 2-D donde una de esas dimensiones es 1.

Por ejemplo:

In [ ]:
a = [1, 2] # lista 1-D
b = [[1, 2]] # Lista de 1 item con una lista de 4 items contenida
c = [[1], [2]] # Lista de 4 items, cada uno una lista de 1 item
d = [[1,2],[3,4]] # Lista de 2 items, cada uno una lista de 2 items

#Crear arrays
A = np.array(a)
B = np.array(b)
C = np.array(c)
D = np.array(d)

print(A)
print(B)
print(C)
print(D)

# Comparar el tipo de a y A
print(type(a))
print(type(A))

[1 2]
[[1 2]]
[[1]
 [2]]
[[1 2]
 [3 4]]
<class 'list'>
<class 'numpy.ndarray'>


Las dimensiones de los arrays se pueden verificar de la siguiente forma. Noten la diferencia entre un array 1-D contra uno 2-D. A su vez, vean que las dimensiones las da en forma de array, por lo que uno puede obtener el numero de filas y columnas por separado:

In [ ]:
# Dimensiones
print(A.shape)
print(B.shape)
print(C.shape)
print(D.shape)

# Chequear una dimensión específica
print('numero de columnas ', C.shape[1])

#iterar por todas las filas
for x in range(B.shape[1]): #iterar por todas las columnas de B
  print(B[:,x])

(2,)
(1, 2)
(2, 1)
(2, 2)
numero de columnas  1
[1]
[2]


Numpy incluye todas las operaciones de matrices típicas, incluyendo producto matricial, prodctos elemento a elemeno, transpuesta, inversa y demás.

Noten que la transpuesta de un elemento 1-D no existe, devuelve el mismo array.

In [ ]:
# Transpuesta
print(A.T)
print(B.T)
print(C.T)
print(D.T)

print(' ')
# Producto elemento a elemento
print(B.T*C)
print(D*D)

print(' ')
# Producto Matricial
print(B@C)
print(D@C)
print(D@D)
print(B@D@C)

[1 2]
[[1]
 [2]]
[[1 2]]
[[1 3]
 [2 4]]
 
[[1]
 [4]]
[[ 1  4]
 [ 9 16]]
 
[[5]]
[[ 5]
 [11]]
[[ 7 10]
 [15 22]]
[[27]]


La conversión de un array 1-D a uno 2-D (o cualquier cambio de dimensiones), puede realizarse mediante la función `reshape`

In [ ]:
# convertir a vector columna
Aprime = np.reshape(A,(-1,1)) # el -1 indica que queda libre (s/ necesario)
print(Aprime)

print(' ')
# Convertir a vector fila
Bprime = np.reshape(A,(1,-1)) # el -1 indica que queda libre (s/ necesario)
print(Bprime)

[[1]
 [2]]
 
[[1 2]]


Numpy contiene además preseteadas ciertas matrices elementales, como la matriz constante, la matriz identidad y matrices de ceros:

In [ ]:
# Matriz de 0's
ZERO = np.zeros((2,3))
print(ZERO)

print('')
# Matriz identidad
EYE = np.eye(2)
print(EYE)

print(' ')
# Matriz constante
CTE = np.ones((4,1))
print(CTE)

print(' ')
# Secuencia de numeros
print(np.linspace(0,10,21)) # 21 numeros de 0 a 10

print(' ')
# Números random entre 0 y 1 (uniforme)
print(np.random.random((3,5)))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 0.]
 [0. 1.]]
 
[[1.]
 [1.]
 [1.]
 [1.]]
 
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
 
[[0.97458033 0.71642686 0.74073625 0.70684173 0.81853545]
 [0.52573732 0.41496952 0.26838071 0.13686041 0.03015708]
 [0.7788166  0.02447294 0.16206211 0.23314641 0.92877672]]


¿Para qué preseteamos una matriz de un tamaño? Para pre-asignar memoria RAM a esa variable. Luego la iremos modificando (por ejemplo, en un `for` loop).

Otra cosa útil es crear un array vacío, para casos donde el tamaño final del array no es conocido y e iremos agregandoles cosas (en un `for` loop, por ejemplo).

In [ ]:
a = [] # lista vacia
a_array = np.array(a) # ya convertir en vector/matriz

print(a_array)
print(type(a_array))

[]
<class 'numpy.ndarray'>


Una ventaja de trabajar con arrays es que es muy simple filtrar datos. La indexación es igual que para listas, pero se pueden aplicar criterios booleanos para la depuración.

Por ejemplo, tomemos el siguiente array y quedemosnos con todos los números menores a 0.5:

In [ ]:
array = np.random.random((1,10))
print(array)

subset = array[array < 0.5]
print(subset)

[[0.18679674 0.59219787 0.11369875 0.32383795 0.62159862 0.81727297
  0.25827427 0.05970263 0.26367097 0.33331693]]
[0.18679674 0.11369875 0.32383795 0.25827427 0.05970263 0.26367097
 0.33331693]


Recuerdan que dijimos que los booleanos son `True` o `Falso`. Bueno, ¡también se comportan como 1 y 0!

Esto es **clave** porque nos permite contar (lo vamos a usar mucho).

In [ ]:
Ntrue = np.sum(array<0.5)
print('Cantidad de ciertos',Ntrue)

Ntot = array.shape[1] # Tomo el segundo valor porque es un vector fila
print('Cantidad de datos',Ntot)

print('Porcentaje de ciertos',Ntrue/Ntot)

Cantidad de ciertos 7
Cantidad de datos 10
Porcentaje de ciertos 0.7


#### Broadcasting

Una de las grandes funcionalidades de Numpy es la capacidad de extender y generalizar operaciones sin necesidad de desarrollar loops o asegurar que todos los elementos tengan las mismas dimensiones, lo que ahorra tiempo y memoria.

Por ejemplo, si a todos los elementos de un vector se les quiere sumar una constante, simplemente se puede escribir:

In [ ]:
a = np.array([1,2,3,4])
b = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

print(a+1) # Sumar una constante a un vector

print(b+a) # Sumar un vector a cada fila de una matriz

[2 3 4 5]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


Esta capacidad se puede utilizar para reducir enormemente el costo computacional de ciertas operaciones, como veremos más adelante

### Funciones

A veces hay ciertas líneas de código que usamos repetidamente. En esos casos es conveniente generar un bloque función que puede ser llamado cuando sea necesario. Por ejemplo, podemos crear nuestra propia función para calcular la norma de un vector:

In [ ]:
def norma(x):
  temp = 0
  for vals in x:
    temp += vals**2
  return np.sqrt(temp)

a = np.array([1, 2, 3, 4])
# Comparación entre nuestra función y la disponible en numpy
print(norma(a), np.linalg.norm(a))

5.477225575051661 5.477225575051661


## Ejericio

Cerremos con un mini-ejercicio. Se tiene el vector `a = [1, 2, 3, 4, 5]`. El objetivo es el siguiente:

* Construya un vector `b` de igual dimensión que tenga en cada celda la sumatoria acumulada al momento de `a` (Es decir, les tiene que dar `[1, 3, 6, 10, 15]`). Utilice un `for` loop
* Luego, encuentre cuántos valores son menores a 5, e imprimálos en pantalla.

In [ ]:
# como hago un for loop donde recorro los valores de un vector y los voy sumando, poniendo el resultado en un nuevo vector

a = np.array([1, 2, 3, 4, 5])

b = np.zeros(a.shape)
sum = 0
for i in range(a.shape[0]):
  sum = sum + a[i]
  b[i] = sum

print(b)
print(np.sum(b<5))
print(b[b<5])

[ 1.  3.  6. 10. 15.]
2
[1. 3.]


Ahora, al `loop` anterior agregue lo siguiente.
* Si el valor b(i) es mayor a 5, indique el valor e imprima cuánto mayor que 5 es: '7 es 2 mayor que 5'

Esta es una herramiento de debugueo super útil.

In [ ]:
a = np.array([1, 2, 3, 4, 5])

b = np.zeros(a.shape)
sum = 0
for i in range(a.shape[0]):
  sum = sum + a[i]
  b[i] = sum
  if b[i]>5:
    print(b[i],'es',b[i]-5,'mayor que 5')

print(b)
print(np.sum(b<5))
print(b[b<5])

6.0 es 1.0 mayor que 5
10.0 es 5.0 mayor que 5
15.0 es 10.0 mayor que 5
[ 1.  3.  6. 10. 15.]
2
[1. 3.]


Imprimiendo cosas parciales es mucho más fácil detectar errores. ¡Ténganlo en mente!