<a href="https://colab.research.google.com/github/mbalbi/ciencia_de_datos/blob/main/notebooks/practica_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<!--NAVIGATION-->
| [Tabla de contenidos](../README.md) | [Probabilidad y Variables Aleatorias](practica_1.ipynb) >

#Clase 1: Introducción a Python

El objetivo de la clase de hoy es amigarnos un poco con Python como lenguage de programación y cubrir ciertas operaciones básicas a partir de las cuales iremos construyendo a lo largo del cuatrimestre.

Usamos Google Colab nos permite programar y correr códigos de Python sin tener que preocuparnos por la instalación de python mismo o de programas específicos. A su vez, nos permite utilizar recursos de Google en la nube para el procesamiento, evitando así la necesidad de una computadora particularmente capaz.

Google Colab, como se ve, permite combinar texto y código de forma tal de generar reportes o documentos, y aprovecharemos esto para el desarrollo de los trabajos prácticos.

##Versión de Python

Una de las grandes ventajas de python es el número de librerías (por decirlo de alguna manera, paquetes de funciones) disponibles en forma libre que se ajustan a la medida del problema que tengamos que resolver. La contracara de esto es que se debe tener cuidado con la compatibilidad de estas librerías con la versión de python que se está corriendo.

En Google Colab se puede elegir la versión de python yendo a `Runtime --> Change Runtime Type`. Para verificar la misma, se puede hacer:

In [ ]:
!python --version

Python 3.7.13


No esperamos que a lo largo del curso nos encontremos con problemas de compatibilidad, pero sepan que puede ocurrir y tengan la costumbre de verificarlo.

##Introducción a Python

###Tipos de datos
Lo primero que tenemos que reconocer son los tipos de datos que podemos encontrarnos en Python.

####Números

Por un lado tenemos los números: Números naturales (`integer`) y números reales (`float`). A diferencia de otros lenguages, la diferencia entre ambos es explicita en Python:**bold text**

In [ ]:
a = 4 # a es un integer
b = 7. # b es un float

Podemos chequear el datatype de una variable con la función `tye()`. Para ver el resultado que entrega la función, usaremos la función `print()`.

In [ ]:
print(type(a)) # Imprime el type de a
print(type(b)) # Imprime el type de b

<class 'int'>
<class 'float'>


Con los números se pueden realizar las operaciones matemáticas típicas (sumas, restas, multiplicaciones y divisiones).

In [ ]:
print(a + 1)   # Suma
print(a - 1)   # Resta
print(a * 2)   # Multiplicación
print(a ** 2)  # Potencia
print(a / 2)   # División

print(b + 1)   # Suma
print(b - 1)   # Resta
print(b * 2)   # Multiplicación
print(b ** 2)  # Potencia
print(b / 2)   # División

5
3
8
16
2.0
8.0
6.0
14.0
49.0
3.5


Noten que las operaciones aplican tanto para `integers` como `floats`. Sin embargo, la division de un `integer` da como resultado un `float`. Se debe tener cuidado con esto cuando este valor necesita ser un número natural (por ejemplo, para referirse a la columna de una matriz). Para convertir el valor, se puede usar la función `int()`, que trunca la variable al número entero.

In [ ]:
print(int(a/2))
print(int(b/2))

2
3


Otra opción es usar el operador `//`, que devuelve el mismo resultado que `int(x/y)` pero respeta el tipo de variable original.

In [ ]:
print(a // 2)
print(a // 2.0)
print(b // 5)
print(b // 5.0)

2
2.0
1.0
1.0


Los resultados de las operaciones vistas arriba podemos guardarlas ya sea en nuevas variables como sobreescribiendo una ya existente. Para esto último existen formatos más compactos como se muestra a continuación.

In [ ]:
c = a + 2 # Suma 2 en una nueva variable 'c'
print(c)

a = a + 1 # Suma 1 y reemplaza a 'a'
print(a)

b += 1 # Suma 1 y reemplaza a 'b'
print(b)

b *= 2 # Multiplica por 2 y reemplaza a 'b'
print(b)

6
5
8.0
16.0


####Texto

El otro tipo de variable que nos encontramos seguido es el Texto (`string`). Si bien no solemos realizar muchas operaciones con variables de texto propiamente dichas, la suma de las mismas resulta en un concatenamiento.

In [ ]:
hello = 'hello' # ''
world = "world" # "" es lo mismo, no importa
Oracion = hello + ' ' + world + '!'
print(Oracion)

hello world!


####Variables lógicas
Python permite a su vez trabajar con variables booleanas (`True` y `False`) para verificar si se cumplen ciertas condiciones:

In [ ]:
t, f = True, False
print(type(t))

<class 'bool'>


Las distintas operaciones booleanas (AND, OR, NOT, XOR) se encuentran todas definidas. Como recordartorio, AND es `True` cuando ambas variables son `True`, OR es `True` si alguna de las variables es `True`, NOT es `True` cuando una variable es `False`, y XOR es `True` cuando dos variables son distintas.

In [ ]:
print(t and f) # AND
print(t or f) # OR
print(not t) # NOT
print(t == f)
print(t != f) # XOR

False
True
False
False
True


Las variables lógicas se obienen también como resultado de comparaciones de otro tipos de datos. por ejemplo, números, y son muy útiles para explorar datos y generar filtros.

In [ ]:
print(3 > 3)
print(3 >= 3)
print(5 != 3)
print('hola' == 'hola')
print('hola' == 'chau')
print(5 > 3 and 2 < 1)

False
True
True
True
False
False


###Listas

Una lista es un conjunto arreglado de items, los cuales pueden ser cualquiera de los tipos de datos vistos anteriormente (incluso combinaciones)

In [ ]:
a = [1, 2, 3, 4]
b = [True, 'Perro', 5, 4.0]
c = [[1, 2],[3, 4]]

print(a)
print(b)
print(c)

[1, 2, 3, 4]
[True, 'Perro', 5, 4.0]
[[1, 2], [3, 4]]


Los valores de una lista están indexados de 0 a la longitud de la lista. Esta última puede ser encontrada con la función `len()`. Noten que la longitud de c es dos ya que tiene dos listas dentro de la lista.

In [ ]:
print(len(a))
print(len(b))
print(len(c))

4
4
2


Valores específicos de la lista pueden ser extraídos refiriendose al índice requerido. Una ventaja de python es que números negativos comienzan el conteo desde el final (por ejemplo, -1 es el último lugar de la lista), lo que simplifica el código en algunas situaciones, y evita calcular la longitud de la lista.

In [ ]:
print(a[-1]) # último lugar
print(b[1])  # segundo lugar
print(c[0])  # primer lugar
print(c[0][1]) # toma el segundo valor de la primer lista

4
Perro
[1, 2]
2


También puede tomarse un slice (un conjunto de la lista) de las siguientes formas:

In [ ]:
print(a[1:]) # toma todos los valores a partir del segundo
print(b[0:2]) # toma los dos primeros valores (el tercero excluido)

[2, 3, 4]
[True, 'Perro']


La indexación puede utilizarse cambiar valores de la lista:

In [ ]:
a[3] = '40'
print(a)

b[:2] = ['Hello', 57]
print(b)

[1, 2, 3, '40']
['Hello', 57, 5, 4.0]


Se debe tener cuidado en Python ya que las listas ocupan un mismo espacio en la memoria. Por ejemplo `a = b`hace que ambas variables se refieran al mismo lugar: si cambio una de ellas, ambas lo harán. Veamos el siguiente ejemplo, donde aprenderemos también a agregar items a una lista.

In [ ]:
a = [1, 2, 3, 4] # Defino a
b = a            # b es igual a a
a.append(5)      # Modifico a, agrego 5 al final
print(b)         # b cambia!
b.append(6)      # Modifico b, agrego 6 al final
print(a)         # a cambia!

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


Si esto no es deseable, se debe usar la función `copy()`, que genera una copia de los valores en otro lugar de la memoria:

In [ ]:
a = [1, 2, 3, 4] # Defino a
b = a.copy()     # b es una copia de a
a.append(5)      # Modifico a, agrego 5 al final
print(b)         # b sigue igual!
b.append(6)      # Modifico b, agrego 6 al final
print(a)         # a sigue igual!

[1, 2, 3, 4]
[1, 2, 3, 4, 5]


###Diccionarios

Un diccionario es también un arreglo de items pero que, en vez de trabajar con indices, utiliza palabras clave (llaves/keys) y valores. Por ejemplo, si mi diccionario es un dataset de lluvias, podría tener información acerca de la latitud y longitud de la estación, su nombre, un registro de lluvias diarias, y un indicador de las unidades de trabajo:

In [ ]:
Lluvias = {'estacion':[7.52, -14.4],'ID':'San Rafael', 'data':[3, 4, 0, 0, 5], 
           'unidades':'mm/dia'}

Se puede acceder a los datos del dicionario de varias formas:

In [ ]:
print(Lluvias['ID'])
print(Lluvias.get('data'))

San Rafael
[3, 4, 0, 0, 5]


Imaginemos que tenemos un nuevo dato de lluvia y queremos agregarlo, y además queremos agregar un listado de temperaturas. Para ello podemos hacer

In [ ]:
Lluvias['data'] += [0, 1]
print(Lluvias['data'])

Lluvias['Temp'] = [30, 20, 25, 10, 0]
print(Lluvias['Temp'])

[3, 4, 0, 0, 5, 0, 1]
[30, 20, 25, 10, 0]


###Condicionales e iteraciones

En ejemplo anterior incorporamos valores o creamos una nueva entrada en el diccionario asumiendo que ya sabíamos que existía o no lo que necesitabamos. En el caso general, sería necesario revisar esto para no generar problemas. Podemos usar entonces `if` statements con ese fin, con el código realizando la operación conveniente en cada caso:

In [ ]:
Lluvias = {'estacion':[7.52, -14.4],'ID':'San Rafael', 'data':[3, 4, 0, 0, 5], 
           'unidades':'mm/dia'}

if 'data' in Lluvias:       # Chequea si existe una llave data
  Lluvias['data'] += [0, 1]  # Agrega valores
else:                       # Caso contrario
  Lluvias['data'] = [0, 1]   # Crea una nueva entrada

print(Lluvias['data'])

if 'temp' in Lluvias:       # Chequea si existe una llave data
  Lluvias['temp'] += [30, 20, 25, 10, 0]  # Agrega valores
else:                       # Caso contrario
  Lluvias['temp'] = [30, 20, 25, 10, 0]   # Crea una nueva entrada

print(Lluvias['temp'])

[3, 4, 0, 0, 5, 0, 1]
[30, 20, 25, 10, 0]


Es importante notar que Python trabaja con indentaciones. Es decir, luego de colocar el statement `if` este se debe terminar con dos puntos, y luego TODO lo que se encuentre indentado (con la misma indentación) se lo considera dentro de ese bloque if. El final de bloque no se indica explicitiamente, sino simplemente terminando la indentación.

Si quisieramos iterar a traves de los valores de una lista, podemos utilizar distintas estrategias, mostradas a continuación que muestran la eficiencia de Python para tomar valores y simplificar la notación:

In [ ]:
a = [1, 3, 5, 7]

i = 0 # Definir una variable para recorrer los indices
while i < len(a): # Mientras la variable este dentro del rango
  print(i, a[i]) # Imprimir indice y valor de la lista
  i += 1

print(' ')
for i in range(len(a)): # Generar una iteracion entre los indices de la lista
  print(i, a[i]) # Imprimir indice y valor

print(' ')
for idx,ai in enumerate(a): # Extraer los indices y valores de la lista
  print(idx, ai) # Imprimir indice y valor

0 1
1 3
2 5
3 7
 
0 1
1 3
2 5
3 7
 
0 1
1 3
2 5
3 7


El último método mostrado es particularmente potente, y muy útil para diccionarios. Compare el código en estos dos ejemplos:

In [ ]:
Lluvias = {'estacion':[7.52, -14.4],'ID':'San Rafael', 'data':[3, 4, 0, 0, 5], 
           'unidades':'mm/dia'}

for i in range(len(Lluvias)):
  print(list(Lluvias.keys())[i], Lluvias[list(Lluvias.keys())[i]])

print(' ')
for keys in Lluvias:
  print(keys, Lluvias[keys])

estacion [7.52, -14.4]
ID San Rafael
data [3, 4, 0, 0, 5]
unidades mm/dia
 
estacion [7.52, -14.4]
ID San Rafael
data [3, 4, 0, 0, 5]
unidades mm/dia


Esto solía ser más importante en versiones anteriores de Python cuando los diccionarios eran "no ordenados". En las últimas versiones los diccionarios son ordenados igual que las listas, por los que la indexación funciona.

###Numpy

Mencionamos antes que existen varias librerías de Python que incorporan funcionalides clave para la solución de problemas. La principal es Numpy, que incopora un nuevo tipo de data (`arrays`) y muchas herramientas de operación matricial. Para agregar una librería en su conjunto, se hace lo siguiente.

In [ ]:
import numpy as np

Un array se crea a partir de una lista de Python, y es a fin de cuentas una matriz. La principal diferencia con otros lenguajes es que, en python, los arrays 1-D no differencian entre vectores columna y vectores filas. Si se quiere especificar, se debe crear un array 2-D donde una de esas dimensiones es 1.

Por ejemplo:

In [ ]:
a = [1, 2] # lista 1-D
b = [[1, 2]] # Lista de 1 item con una lista de 4 items contenida
c = [[1], [2]] # Lista de 4 items, cada uno una lista de 1 item
d = [[1,2],[3,4]] # Lista de 2 items, cada uno una lista de 2 items

#Crear arrays
A = np.array(a)
B = np.array(b)
C = np.array(c)
D = np.array(d)

print(A)
print(B)
print(C)
print(D)

# Comparar el tipo de a y A
print(type(a))
print(type(A))

[1 2]
[[1 2]]
[[1]
 [2]]
[[1 2]
 [3 4]]
<class 'list'>
<class 'numpy.ndarray'>


Las dimensiones de los arrays se pueden verificar de la siguiente forma. Noten la diferencia entre un array 1-D contra uno 2-D. A su vez, vean que las dimensiones las da en forma de array, por lo que uno puede obtener el numero de filas y columnas por separado:

In [ ]:
# Dimensiones
print(A.shape)
print(B.shape)
print(C.shape)
print(D.shape)

# Chequear una dimensión específica
print('numero de columnas ', C.shape[1])

(2,)
(1, 2)
(2, 1)
(2, 2)
numero de columnas  1


Numpy incluye todas las operaciones de matrices típicas, incluyendo producto matricial, prodctos elemento a elemeno, transpuesta, inversa y demás.

Noten que la transpuesta de un elemento 1-D no existe, devuelve el mismo array.

In [ ]:
# Transpuesta
print(A.T)
print(B.T)
print(C.T)
print(D.T)

print(' ')
# Producto elemento a elemento
print(B.T*C)
print(D*D)

print(' ')
# Producto Matricial
print(B@C)
print(D@C)
print(D@D)
print(B@D@C)

[1 2]
[[1]
 [2]]
[[1 2]]
[[1 3]
 [2 4]]
 
[[1]
 [4]]
[[ 1  4]
 [ 9 16]]
 
[[5]]
[[ 5]
 [11]]
[[ 7 10]
 [15 22]]
[[27]]


La conversión de un array 1-D a uno 2-D (o cualquier cambio de dimensiones), puede realizarse mediante la función `reshape`

In [ ]:
# convertir a vector columna
Aprime = np.reshape(A,(-1,1)) # el -1 indica que queda libre (s/ necesario)
print(Aprime)

print(' ')
# Convertir a vector fila
Bprime = np.reshape(A,(1,-1)) # el -1 indica que queda libre (s/ necesario)
print(Bprime)

[[1]
 [2]]
 
[[1 2]]


Numpy contiene además preseteadas ciertas matrices elementales, como la matriz constante, la matriz identidad y matrices de ceros:

In [ ]:
# Matriz de 0's
ZERO = np.zeros((2,3))
print(ZERO)

print('')
# Matriz identidad
EYE = np.eye(2)
print(EYE)

print(' ')
# Matriz constante
CTE = np.ones((4,1))
print(CTE)

print(' ')
# Secuencia de numeros
print(np.linspace(0,10,21)) # 21 numeros de 0 a 10

print(' ')
# Números random entre 0 y 1 (uniforme)
print(np.random.random((3,5)))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 0.]
 [0. 1.]]
 
[[1.]
 [1.]
 [1.]
 [1.]]
 
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
 
[[0.99838845 0.83140517 0.81187714 0.0072142  0.8925101 ]
 [0.93325017 0.16308131 0.96179529 0.3438364  0.70027367]
 [0.94650473 0.14539425 0.61976853 0.20110258 0.76496206]]


Una ventaja de trabajar con arrays es que es muy simple filtrar datos. La indexación es igual que para listas, pero se pueden aplicar criterios booleanos para la depuración.

Por ejemplo, tomemos el siguiente array y quedemosnos con todos los números menores a 0.5:

In [ ]:
array = np.random.random((1,10))
print(array)

subset = array[array < 0.5]
print(subset)

[[0.05687784 0.86368256 0.05743397 0.40196829 0.89181021 0.80511387
  0.93096241 0.62645192 0.46687479 0.84695195]]
[0.05687784 0.05743397 0.40196829 0.46687479]


####Broadcasting

Una de las grandes funcionalidades de Numpy es la capacidad de extender y generalizar operaciones sin necesidad de desarrollar loops o asegurar que todos los elementos tengan las mismas dimensiones, lo que ahorra tiempo y memoria.

Por ejemplo, si a todos los elementos de un vector se les quiere sumar una constante, simplemente se puede escribir:

In [ ]:
a = np.array([1,2,3,4])
b = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

print(a+1) # Sumar una constante a un vector

print(b+a) # Sumar un vector a cada fila de una matriz

[2 3 4 5]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


Esta capacidad se puede utilizar para reducir enormemente el costo computacional de ciertas operaciones, como veremos más adelante

###Funciones

A veces hay ciertas líneas de código que usamos repetidamente. En esos casos es conveniente generar un bloque función que puede ser llamado cuando sea necesario. Por ejemplo, podemos crear nuestra propia función para calcular la norma de un vector:

In [ ]:
def norma(x):
  temp = 0
  for vals in x:
    temp += vals**2
  return np.sqrt(temp)

a = np.array([1, 2, 3, 4])
# Comparación entre nuestra función y la disponible en numpy
print(norma(a), np.linalg.norm(a))

5.477225575051661 5.477225575051661


##Ejercicio

A modo de cierre, vamos a desarrollar 2 funciones para calcular las distancias entre todos los puntos de un grilla. Este dato es importante, por ejemplo, para el desarrollo de modelos digitales de un terreno, ya que la interpolación de la elevación depende de las distancias del punto de análisis a todos los puntos con datos concretos.

###Datos

Los puntos a estudiar son imagenes de 32x32 pixeles RGB (3 valores de intensidad), que a fin de cuenta podemos pensarlo como 3072 datos distintos que definen a una imagen. En total tenemos 50000 imagenes conocidas y 10000 imagenes desconocidas. Para estas 1000, hay que calcular las distancias con las otras 50000.

Primero, descarguemos el Dataset y las funciones que capturan la data

In [ ]:
from six.moves import cPickle as pickle
import numpy as np
import os
import platform

def load_pickle(f):
    version = platform.python_version_tuple()
    if version[0] == '2':
        return  pickle.load(f)
    elif version[0] == '3':
        return  pickle.load(f, encoding='latin1')
    raise ValueError("invalid python version: {}".format(version))

def load_CIFAR_batch(filename):
  """ load single batch of cifar """
  with open(filename, 'rb') as f:
    datadict = load_pickle(f)
    X = datadict['data']
    Y = datadict['labels']
    X = X.reshape(10000, 3, 32, 32).transpose(0,2,3,1).astype("float")
    Y = np.array(Y)
    return X, Y

def load_CIFAR10(ROOT):
  """ load all of cifar """
  xs = []
  ys = []
  for b in range(1,6):
    f = os.path.join(ROOT, 'data_batch_%d' % (b, ))
    X, Y = load_CIFAR_batch(f)
    xs.append(X)
    ys.append(Y)    
  Xtr = np.concatenate(xs)
  Ytr = np.concatenate(ys)
  del X, Y
  Xte, Yte = load_CIFAR_batch(os.path.join(ROOT, 'test_batch'))
  return Xtr, Ytr, Xte, Yte

# Descargar CIFAR10
!wget http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
!tar -xzvf cifar-10-python.tar.gz
!rm cifar-10-python.tar.gz 

--2022-08-17 14:57:00--  http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
Resolving www.cs.toronto.edu (www.cs.toronto.edu)... 128.100.3.30
Connecting to www.cs.toronto.edu (www.cs.toronto.edu)|128.100.3.30|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 170498071 (163M) [application/x-gzip]
Saving to: ‘cifar-10-python.tar.gz’

cifar-10-python.tar 100%[===================>] 162.60M  56.3MB/s    in 2.9s    

2022-08-17 14:57:05 (56.3 MB/s) - ‘cifar-10-python.tar.gz’ saved [170498071/170498071]

cifar-10-batches-py/
cifar-10-batches-py/data_batch_4
cifar-10-batches-py/readme.html
cifar-10-batches-py/test_batch
cifar-10-batches-py/data_batch_3
cifar-10-batches-py/batches.meta
cifar-10-batches-py/data_batch_2
cifar-10-batches-py/data_batch_5
cifar-10-batches-py/data_batch_1


In [ ]:
# Cargar la data CIFAR-10 como viene.
cifar10_dir = 'cifar-10-batches-py'

# Borrar valores anteriores para evitar problemas de memoria
try:
   del X_train, y_train
   del X_test, y_test
   print('Clear previously loaded data.')
except:
   pass

X_train, y_train, X_test, y_test = load_CIFAR10(cifar10_dir)

# Veamos el tamaño de los datos.
print('Training data shape: ', X_train.shape)
print('Test data shape: ', X_test.shape)


Training data shape:  (50000, 32, 32, 3)
Test data shape:  (10000, 32, 32, 3)


###Manejo de datos

Lo primero que hay que hacer es reformular la data a forma de matriz, con cada fila representado una imagen y cada columna representando un valor de un pixel:

In [ ]:
# Reorganizar la data en filas
X_train = np.reshape(X_train, (X_train.shape[0], -1))
X_test = np.reshape(X_test, (X_test.shape[0], -1))
print(X_train.shape, X_test.shape)

(50000, 3072) (10000, 3072)


Como no nos va a dar la memoria RAM, reduzcamos la cantidad de datos a 5000 datos conocidos y 500 desconocidos.

In [ ]:
X_train = X_train[:5000,:]
X_test = X_test[:500,:]

###Desarrollo de funciones

Ahora vamos a crear 2 funciones para calcular las distancias. Una utilizando 2 for loops (iterando entre todos los puntos), y otra aprovechando las capacidades de broadcasting de numpy. ¡Veamos cuanto tarda en correr cada una!

In [ ]:
def distancias2loops(Xtrain,Xtest):
    num_test = Xtest.shape[0]
    num_train = Xtrain.shape[0]
    dists = np.zeros((num_test, num_train))
    for i in range(num_test):
      for j in range(num_train):
        d_vec = Xtest[i,:]-Xtrain[j,:]
        dists[i,j] = np.sqrt(np.sum(d_vec**2))
    return dists

def distanciasnoloops(Xtrain,Xtest):
    num_test = Xtest.shape[0]
    num_train = Xtrain.shape[0]
    dists = np.zeros((num_test, num_train)) 
    d_x = Xtest
    d_y = np.transpose(Xtrain)
    dists = (np.sqrt(np.transpose(np.sum(d_x**2,1)+
                                  np.transpose(np.transpose(np.sum(d_y**2,0))
                                  -2*np.matmul(d_x,d_y)))))
    return dists

In [ ]:
def time_function(f, *args):
    """
    Call a function f with args and return the time (in seconds) that it took to execute.
    """
    import time
    tic = time.time()
    f(*args)
    toc = time.time()
    return toc - tic

In [ ]:
two_loop_time = time_function(distancias2loops, X_train,X_test)
print('2 loops tarda %f seconds' % two_loop_time)

no_loop_time = time_function(distanciasnoloops, X_train,X_test)
print('Sin loops tarda %f seconds' % no_loop_time)


2 loops tarda 41.849501 seconds
Sin loops tarda 0.581736 seconds


Miren la diferencia!

###Verificación

Por último, asegurémosnos que las matrices sean iguales y que está todo OK.

In [ ]:
dists = distanciasnoloops(X_train,X_test)
dists_two = distancias2loops(X_train,X_test)

# Norma de orden 2
diferencia = np.linalg.norm(dists - dists_two, ord='fro')
print('Difference was: %f' % (diferencia, ))
if diferencia < 0.001:
    print('TODO OK!')
else:
    print('OOF, ¿Dónde me equivoqué?')

Difference was: 0.000000
TODO OK!
